package com.example.blushfinance.db; // Or your models package

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a single income item.
 * This class is now a Room Entity, meaning it defines a table in the database.
 */
@Entity(tableName = "income_cards") // Specifies the table name for this entity
public class IncomeCard {

    @PrimaryKey(autoGenerate = true) // Marks 'id' as the primary key, auto-generated by Room
    public int id;                   // Unique ID for each income record in the database

    private String name;    // Name of the income source (e.g., "Salary", "Freelance")
    private float amount;   // The monetary amount of the income
    private int itemColor;  // Color used for UI representation (card background, pie slice)

    /**
     * Constructor for creating an IncomeCard.
     * Room can use this constructor. The 'id' is auto-generated by Room.
     * @param name The name or category of the income.
     * @param amount The amount of the income.
     * @param itemColor The color associated with this income item.
     */
    public IncomeCard(String name, float amount, int itemColor) {
        this.name = name;
        this.amount = amount;
        this.itemColor = itemColor;
    }

    // --- Getters ---
    // Room uses these (or public fields) to read data when fetching from the database.

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public float getAmount() {
        return amount;
    }

    public int getItemColor() {
        return itemColor;
    }

    // --- Setters ---
    // Room might use these if it needs to set fields after creating an instance
    // (e.g., if using a no-arg constructor and then setting fields, though less common
    // if a suitable constructor is available).
    // For the 'id' field, a setter isn't strictly necessary if it's only auto-generated
    // and you don't manually set it.

    // public void setId(int id) { // Setter for id is not typically needed for auto-generated keys
    //     this.id = id;
    // }

    public void setName(String name) {
        this.name = name;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    public void setItemColor(int itemColor) {
        this.itemColor = itemColor;
    }
}
